spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/izohli_lugat_db
    username: izohli_lugat_user
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080